# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
use_bioc: true
bioc_required: true
r_packages:
    - devtools
    - covr
after_success:
    - Rscript -e 'devtools::test(); covr::codecov()'
